#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_PunRealEditorTYPE           130
#define IDD_DIALOG_EDIT                 310
#define IDD_MOBTOOL                     313
#define IDC_TAGNAME                     1004
#define IDC_X                           1004
#define IDC_Y                           1005
#define IDC_Z                           1006
#define IDC_X2                          1007
#define IDC_SCALEX                      1008
#define IDC_Y2                          1008
#define IDC_TRANSFORMGROUP              1009
#define IDC_Z2                          1009
#define IDC_POSITIONTEXT                1010
#define IDC_ROTATIONX                   1011
#define IDC_POSITIONX                   1012
#define IDC_ROTATIONTEXT                1013
#define IDC_SCALETEXT                   1014
#define IDC_SCALEY                      1015
#define IDC_ROTATIONY                   1016
#define IDC_POSITIONY                   1017
#define IDC_SCALEZ                      1018
#define IDC_ROTATIONZ                   1019
#define IDC_POSITIONZ                   1020
#define IDC_COUNTXTEXT                  1022
#define IDC_SIZEXTEXT                   1023
#define IDC_COUNTYTEXT                  1024
#define IDC_SIZEYTEXT                   1025
#define IDC_SCALEX2                     1026
#define IDC_TILECOUNTX                  1026
#define IDC_SCALEX3                     1027
#define IDC_TILECOUNTY                  1027
#define IDC_SCALEX4                     1028
#define IDC_TILESIZEX                   1028
#define IDC_SCALEX5                     1029
#define IDC_TILESIZEY                   1029
#define IDC_TILESELECT                  1030
#define IDC_TILEOPTIONSELECT            1031
#define IDC_TILETYPETEXT                1032
#define IDC_TILEOPTIONTEXT              1033
#define IDC_SIZEXTEXT2                  1033
#define IDC_TILECREATEBUTTON            1034
#define IDC_TRANSFORMGROUP2             1035
#define IDC_MONSTERLOAD                 1035
#define IDC_SCALEZ2                     1036
#define IDC_COLORB                      1036
#define IDC_STARTPOSX                   1037
#define IDC_BACKGROUNDCOLORTEXT         1038
#define IDC_STARTPOSY                   1039
#define IDC_SCALEZ3                     1040
#define IDC_COLORR                      1040
#define IDC_SCALEZ4                     1041
#define IDC_COLORG                      1041
#define IDC_CURTILEIMAGE                1042
#define IDC_TILEIMAGE                   1042
#define IDC_NEXTTILEIMAGE               1043
#define IDC_SCALEZ5                     1044
#define IDC_COLORA                      1044
#define IDC_TILEIMAGESELECT             1045
#define IDC_SIZEXTEXT3                  1047
#define IDC_SIZEXTEXT4                  1048
#define IDC_TILEIMAGETEXT               1049
#define IDC_WORK                        1050
#define IDC_WORKTEXT                    1051
#define IDC_COLORSAVE                   1057
#define IDC_TILEOPTION                  1058
#define IDC_TILESAVE                    1059
#define IDC_LINEON                      1060
#define IDC_TILELOAD                    1061
#define IDC_TILECLEAR                   1062
#define IDC_CREATETILECOUNT             1065
#define IDC_TILEROTATION                1066
#define IDC_CHECK1                      1067
#define IDC_EDIT1                       1068
#define IDC_EDIT2                       1069
#define IDC_TOOLOPEN                    1070
#define IDC_CLOSE                       1072
#define IDC_SELECTIMAGE                 1073
#define IDC_EDIT3                       1075
#define IDC_COMBO2                      1076
#define IDC_EDIT5                       1077
#define IDC_EDIT4                       1079
#define IDC_EDIT6                       1080
#define IDC_LIST1                       1081
#define IDC_BUTTON2                     1083
#define IDC_BUTTON3                     1084
#define IDC_LOAD                        1084
#define IDC_BUTTON4                     1085
#define IDC_MONLOAD                     1086
#define ID_GAMEOBJECT                   32771
#define ID_GAMEOBJECT_32772             32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        316
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1085
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
